### ISSUE TITLE
Interactive/notebook version

### ISSUE THREAD

**Issue by stevet40** [bayesn/bayesn#22]
This is a bit open ended, and possibly quite a lot of work...

It would be nice to have a more interactive way of running a small number of light curve fits, or a quick way of launching bayesn on a single supernova light curve file (without creating an input.yaml, and a data table).

For an interactive version, the criteria I can imagine being desirable would be that:
* it can be run in a Jupyter notebook, or similar environment;
* it can be easily set up and launched from within a custom python script; and
* it can operate on data already loaded in memory (e.g. potentially from a non-SNANA format file loaded in by a user).

For a quick single light curve fit, I think the ideal (for me) would be having something that can be pointed to a single SNANA format light curve file (assuming it can get the peak MJD, redshift, etc. from the header), given a few command line flags, and run.

I suspect that most of the pieces needed for these are there, just perhaps not exposed to the user/documented.

**Comment by mattgrayling** [comment]
I have created new class methods called `fit` and `fit_from_file` which are designed specifically for fitting single light curves using data already loaded into memory, or for fitting data from a single SNANA format light curve file. Once these have been tested by users, I will close this issue

**Comment by mattgrayling** [comment]
I'm closing this now as I think these are working as required, but feel free to reopen if there is any new functionality needed
